### ISSUE TITLE
Error on try run on godot 4.3

### ISSUE THREAD

**Issue by edson-dev** [mrjsj/godot-duckdb#6]
Hello,
im testing this asset on 4.2 but 4.3 have some improvements. But when I try to start on 4.3 the extension break with no log. there any way to enable it so I can at last see why it don't work on 4.3?

**Comment by mrjsj** [comment]
Thanks for reporting this issue.
I will try to re-compile with Godot 4.3 later today.

**Comment by mrjsj** [comment]
@edson-dev
I have closed the issue, but still need to create the release.
When the release is created, I will re-test it, and you'll be able to download the compiled libraries from the release page.

I need to update the asset on Godot Asset Store too, but that requires approval from Godot moderators, so it could take a couple of days before you can download it from the asset store.
