### ISSUE TITLE
Error on asset lib

### ISSUE THREAD

**Issue by edson-dev** [mrjsj/godot-duckdb#9]
im testing the asset lib and there are some errors?
- it was only listing on godot 4.3 and not on 4.2 anymore.
- the installation for 4.3 looks like don't run and keeps wo response.
- I tried the build runtime, but with the demo project I cant run the project when its not inside the repository folder.
how can I encapsulate the runtime and addon folder to insert on other projects?

**Comment by mrjsj** [comment]
- i'm not too familiar with how godot asset store handles asset libs across version, however you can still download the 4.2 version from the branch here: https://github.com/mrjsj/godot-duckdb/tree/assetlib-v0.4.0-godot-4.2.2

- if you just install the asset lib, there's no code implementation, so you need to create a script similar to this: https://github.com/mrjsj/godot-duckdb?tab=readme-ov-file#how-to-use

- i assume you're on a windows pc? i haven't had the chance to test on windows, so i'm not familiar with any issues related to it, however on macOS i have tested both the demo project, and installing from asset store in a fresh project and have no issues at all unfortunately.

**Comment by edson-dev** [comment]
im having a error "error(-1): no debug info in PE/COFF executable" when trying to execute the addon, this error for some reason looks like corrupt the project. I tried install the assetlib version, download the din and replace and run the code example on the release, none of then seens working. Ty I gonna see how I gonna follow

**Comment by mrjsj** [comment]
@edson-dev Hey it seems this error has finally been resolved during investigation of #11 
Please check newest release: https://github.com/mrjsj/godot-duckdb/releases/tag/v0.6.2-godot-4.4.0
